export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ALL_COMPANYS = 'GET_ALL_COMPANYS';
export const GET_ALL_COMPANYS_BY_ADMINUSER_ID = 'GET_ALL_COMPANYS_BY_ADMINUSER_ID';
export const GET_COMPANY_BY_COMPANY_ID = 'GET_COMPANY_BY_COMPANY_ID';
export const COMPANY_LOADING = 'COMPANY_LOADING';
export const CLEAR_CURRENT_COMPANY = 'CLEAR_CURRENT_COMPANY';
export const COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const DELETE_COMPANY_BY_COMPANY_ID = 'DELETE_COMPANY_COMPANY_ID';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_BY_POSITION_ID = 'GET_ALL_USERS_BY_POSITION_ID';
export const GET_ALL_USERS_BY_COMPANY_ID = 'GET_ALL_USERS_BY_COMPANY_ID';
export const GET_USER_BY_USER_ID = 'GET_USER_BY_USER_ID';
export const USER_LOADING = 'USER_LOADING';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER_BY_USER_ID = 'DELETE_USER_USER_ID';

export const GET_ALL_ONETOONES = 'GET_ALL_ONETOONES';
export const GET_ALL_ONETOONES_BY_USER_ID = 'GET_ALL_ONETOONES_BY_USER_ID';
export const GET_ONETOONE_BY_ONETOONE_ID = 'GET_ONETOONE_BY_ONETOONE_ID';
export const ONETOONE_LOADING = 'ONETOONE_LOADING';
export const CLEAR_CURRENT_ONETOONE = 'CLEAR_CURRENT_ONETOONE';
export const ONETOONE_NOT_FOUND = 'ONETOONE_NOT_FOUND';
export const CREATE_ONETOONE = 'CREATE_ONETOONE';
export const DELETE_ONETOONE_BY_ONETOONE_ID = 'DELETE_ONETOONE_ONETOONE_ID';

// export const GET_ALL_STOPS = 'GET_ALL_STOPS';
// export const GET_ALL_STOPS_BY_USER_ID = 'GET_ALL_STOPS_BY_USER_ID';
// export const GET_ALL_STOPS_BY_TRIP_ID = 'GET_ALL_STOPS_BY_TRIP_ID';
// export const GET_STOP_BY_STOP_ID = 'GET_STOP_BY_STOP_ID';
// export const STOP_LOADING = 'STOP_LOADING';
// export const CLEAR_CURRENT_STOP = 'CLEAR_CURRENT_STOP';
// export const STOP_NOT_FOUND = 'STOP_NOT_FOUND';
// export const CREATE_STOP = 'CREATE_STOP';
// export const DELETE_STOP_BY_STOP_ID = 'DELETE_STOP_BY_STOP_ID';
//
// export const GET_ALL_DAYS = 'GET_ALL_DAYS';
// export const GET_ALL_DAYS_BY_USER_ID = 'GET_ALL_DAYS_BY_USER_ID';
// export const GET_ALL_DAYS_BY_STOP_ID = 'GET_ALL_DAYS_BY_STOP_ID';
// export const GET_DAY_BY_DAY_ID = 'GET_DAY_BY_DAY_ID';
// export const DAY_LOADING = 'DAY_LOADING';
// export const CLEAR_CURRENT_DAY = 'CLEAR_CURRENT_DAY';
// export const DAY_NOT_FOUND = 'DAY_NOT_FOUND';
// export const CREATE_DAY = 'CREATE_DAY';
// export const DELETE_DAY_BY_DAY_ID = 'DELETE_DAY_BY_DAY_ID';
//
// export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
// export const GET_ALL_EVENTS_BY_USER_ID = 'GET_ALL_EVENTS_BY_USER_ID';
// export const GET_ALL_EVENTS_BY_DAY_ID = 'GET_ALL_EVENTS_BY_STOP_ID';
// export const GET_EVENT_BY_EVENT_ID = 'GET_EVENT_BY_EVENT_ID';
// export const EVENT_LOADING = 'EVENT_LOADING';
// export const CLEAR_CURRENT_EVENT = 'CLEAR_CURRENT_EVENT';
// export const EVENT_NOT_FOUND = 'EVENT_NOT_FOUND';
// export const CREATE_EVENT = 'CREATE_EVENT';
// export const DELETE_EVENT_BY_EVENT_ID = 'DELETE_EVENT_BY_EVENT_ID';

//export const DELETE_USER_BY_USER_ID = 'DELETE_USER_BY_USER_ID';
